//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopbanhoa
{


    public partial class Trangchu
    {

        /// <summary>
        /// KhuyenMaiNB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::shopbanhoa.Product.KhuyenMaiNB KhuyenMaiNB;

        /// <summary>
        /// BanChayNB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::shopbanhoa.Product.BanChayNB BanChayNB;

        /// <summary>
        /// HoaLyNB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::shopbanhoa.Product.HoaLyNB HoaLyNB;

        /// <summary>
        /// HoaHongNB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::shopbanhoa.Product.HoaHongNB HoaHongNB;

        /// <summary>
        /// HoaSenNB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::shopbanhoa.Product.HoaSenNB HoaSenNB;

        /// <summary>
        /// TinTucNB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::shopbanhoa.Product.TinTucNB TinTucNB;
    }
}
